app = "btc-predictor"

[build]
  [build.args]
    PYTHON_VERSION = "3.11"

[env]
  FLASK_APP = "app.py"
  TIMEZONE = "US/Eastern"

[[services]]
  internal_port = 5000
  protocol = "tcp"
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    
  [[services.ports]]
    handlers = ["http"]
    port = 80
    
  [[services.ports]]
    handlers = ["tls"]
    port = 443
    
  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "30s"

[[mounts]]
  source = "btc_data"
  destination = "/app/data"